name: campus_marketplace
description: A marketplace app for university students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^13.0.2
  cloud_functions: ^6.0.0

  # Core packages
  cupertino_icons: ^1.0.6
  
  # Navigation
  go_router: ^13.0.0
  
  # State Management
  provider: ^6.1.1
  
  # UI Components & Image Caching
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  shimmer: ^3.0.0
  
  # Image handling
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  
  # HTTP & API
  http: ^1.2.0
  package_info_plus: ^8.0.0
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  
  # Optional: For animations
  flutter_animate: ^4.5.0
  
  # Optional: For pull to refresh
  pull_to_refresh: ^2.0.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  google_sign_in: ^7.2.0
  
  # BLE packages
  flutter_ble_peripheral: ^1.2.6
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1

  # Geolocation
  geolocator: ^13.0.0

  # Local Database & Connectivity
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section:
  assets:
    - icono_marketplace.png
    - .env
  #   - assets/icons/
  
  # Fonts (optional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icono_marketplace.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icono_marketplace.png"