name: campus_marketplace
description: A marketplace app for university students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.6
  
  # Navigation
  go_router: ^13.0.0
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Image handling
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  
  # HTTP & API
  http: ^1.2.0
  
  # Optional: For animations
  flutter_animate: ^4.5.0
  
  # Optional: For pull to refresh
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section:
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (optional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700