// Lista de carreras disponibles en la universidad
const List<String> MAJORS = [
  'Administración',
  'Antropología',
  'Arquitectura',
  'Arte',
  'Biología',
  'Ciencia Política',
  'Contaduría Internacional',
  'Derecho',
  'Diseño',
  'Economía',
  'Educación Infantil',
  'Estudios Globales',
  'Física',
  'Filosofía',
  'Geociencias',
  'Gobierno y Asuntos Públicos',
  'Historia',
  'Historia del Arte',
  'Ingeniería Ambiental',
  'Ingeniería Biomédica',
  'Ingeniería Civil',
  'Ingeniería de Alimentos',
  'Ingeniería de Sistemas y Computación',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Ingeniería Industrial',
  'Ingeniería Mecánica',
  'Ingeniería Química',
  'Lenguas y Cultura',
  'Literatura',
  'Matemáticas',
  'Medicina',
  'Microbiología',
  'Música',
  'Narrativas Digitales',
  'Psicología',
  'Química',
  'Licenciatura en Artes',
  'Licenciatura en Biología',
  'Licenciatura en Español y Filología',
  'Licenciatura en Filosofía',
  'Licenciatura en Física',
  'Licenciatura en Historia',
  'Licenciatura en Matemáticas',
  'Licenciatura en Química',
];

